### ISSUE TITLE
 Error during setup of component onkyo_custom

### ISSUE THREAD

**Issue by Alessiou78** [fleXible/ha-onkyo-custom#8]
Haoss Version: 2024.3.3

I got this error:
```
Registratore: homeassistant.setup
Fonte: setup.py:390
Prima occorrenza: 23:26:14 (1 occorrenze)
Ultima registrazione: 23:26:14

Error during setup of component onkyo_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 390, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/onkyo_custom/__init__.py", line 170, in async_setup
    HomeAssistantScene.device_state_attributes
AttributeError: type object 'HomeAssistantScene' has no attribute 'device_state_attributes'. Did you mean: 'extra_state_attributes'?
```

**Comment by fleXible** [comment]
@Alessiou78 recently I updated my HomeAssistant installation, too and saw the error, but haven't had time to release the fix. But I'll hope to come around in the next few days.

If you need a fix urgently, manually comment out lines 144-174
